// Fees Structure & Automated Billing Engine - in-memory store
// Integrates with GL revenue accounts, AR, invoicing, SIS and academic calendar.

export type BillingCycle = 'Monthly' | 'Termly' | 'Annual' | 'One-time' | 'Custom';
export type StructureStatus = 'Draft' | 'Pending Approval' | 'Approved' | 'Archived';
export type InvoiceStatus = 'Draft' | 'Posted' | 'Paid' | 'Partially Paid' | 'Cancelled';

export interface FeeItem {
  id: string;
  name: string;
  glAccountCode: string; // links to GL revenue account
  amount: number;
  cycle: BillingCycle;
  mandatory: boolean;
  appliesTo?: 'All' | 'Boarding' | 'Day';
}

export interface FeeStructure {
  id: string;
  code: string;
  name: string;
  academicYear: string;
  level?: string;         // e.g. "Form 3"
  className?: string;     // e.g. "Form 3A"
  stream?: string;
  program?: string;
  currency: string;
  version: number;
  parentId?: string;      // previous version
  status: StructureStatus;
  effectiveFrom: string;
  effectiveTo?: string;
  items: FeeItem[];
  createdBy: string;
  createdAt: string;
  approvedBy?: string;
  approvedAt?: string;
  notes?: string;
}

export interface AcademicTerm {
  id: string;
  name: string;           // "Term 1 2026"
  academicYear: string;
  startDate: string;
  endDate: string;
  billingDate: string;    // day invoices auto-generate
}

export interface StudentAssignment {
  id: string;
  studentId: string;
  structureId: string;
  discountPercent?: number;
  scholarshipAmount?: number;
  notes?: string;
  assignedAt: string;
}

export interface GeneratedInvoice {
  id: string;
  invoiceNumber: string;
  studentId: string;
  structureId: string;
  termId?: string;
  date: string;
  dueDate: string;
  lines: { description: string; glAccountCode: string; amount: number }[];
  subtotal: number;
  discount: number;
  total: number;
  status: InvoiceStatus;
  currency: string;
  autoGenerated: boolean;
}

export interface AuditEntry {
  id: string;
  timestamp: string;
  actor: string;
  action: string;
  entity: string;
  entityId: string;
  details: string;
}

// ---------------- Seed data ----------------
export const academicTerms: AcademicTerm[] = [
  { id: 't1', name: 'Term 1 2026', academicYear: '2026', startDate: '2026-01-13', endDate: '2026-04-10', billingDate: '2026-01-05' },
  { id: 't2', name: 'Term 2 2026', academicYear: '2026', startDate: '2026-05-05', endDate: '2026-08-07', billingDate: '2026-04-25' },
  { id: 't3', name: 'Term 3 2026', academicYear: '2026', startDate: '2026-09-01', endDate: '2026-12-04', billingDate: '2026-08-20' },
];

export const initialStructures: FeeStructure[] = [
  {
    id: 'fs1', code: 'FS-F1-2026', name: 'Form 1 Day Scholar - 2026',
    academicYear: '2026', level: 'Form 1', currency: 'USD',
    version: 1, status: 'Approved', effectiveFrom: '2026-01-01',
    items: [
      { id: 'i1', name: 'Tuition Fees', glAccountCode: '4000', amount: 900, cycle: 'Termly', mandatory: true, appliesTo: 'All' },
      { id: 'i2', name: 'Development Levy', glAccountCode: '4000', amount: 150, cycle: 'Termly', mandatory: true, appliesTo: 'All' },
      { id: 'i3', name: 'Sports Levy', glAccountCode: '4000', amount: 50, cycle: 'Termly', mandatory: true, appliesTo: 'All' },
      { id: 'i4', name: 'Registration', glAccountCode: '4200', amount: 100, cycle: 'One-time', mandatory: true },
    ],
    createdBy: 'D. Phiri', createdAt: '2025-11-10', approvedBy: 'Principal', approvedAt: '2025-11-15',
  },
  {
    id: 'fs2', code: 'FS-F3B-2026', name: 'Form 3 Boarding - 2026',
    academicYear: '2026', level: 'Form 3', currency: 'USD',
    version: 1, status: 'Approved', effectiveFrom: '2026-01-01',
    items: [
      { id: 'i1', name: 'Tuition Fees', glAccountCode: '4000', amount: 1200, cycle: 'Termly', mandatory: true },
      { id: 'i2', name: 'Boarding Fees', glAccountCode: '4100', amount: 800, cycle: 'Termly', mandatory: true, appliesTo: 'Boarding' },
      { id: 'i3', name: 'Development Levy', glAccountCode: '4000', amount: 200, cycle: 'Termly', mandatory: true },
      { id: 'i4', name: 'Sports Levy', glAccountCode: '4000', amount: 100, cycle: 'Termly', mandatory: true },
      { id: 'i5', name: 'Meals', glAccountCode: '4100', amount: 100, cycle: 'Termly', mandatory: false, appliesTo: 'Boarding' },
    ],
    createdBy: 'D. Phiri', createdAt: '2025-11-10', approvedBy: 'Principal', approvedAt: '2025-11-15',
  },
];

export const initialAssignments: StudentAssignment[] = [
  { id: 'a1', studentId: '1', structureId: 'fs2', assignedAt: '2026-01-05' },
  { id: 'a2', studentId: '3', structureId: 'fs2', scholarshipAmount: 200, notes: 'Academic excellence scholarship', assignedAt: '2026-01-05' },
  { id: 'a3', studentId: '4', structureId: 'fs1', discountPercent: 10, notes: 'Sibling discount', assignedAt: '2026-01-15' },
];

// ---------------- Helpers ----------------
export function structureTotal(structure: FeeStructure, boardingStatus?: 'Boarding' | 'Day'): number {
  return structure.items
    .filter(i => !i.appliesTo || i.appliesTo === 'All' || i.appliesTo === boardingStatus)
    .filter(i => i.mandatory)
    .reduce((s, i) => s + i.amount, 0);
}

export function structureFullTotal(structure: FeeStructure, boardingStatus?: 'Boarding' | 'Day'): number {
  return structure.items
    .filter(i => !i.appliesTo || i.appliesTo === 'All' || i.appliesTo === boardingStatus)
    .reduce((s, i) => s + i.amount, 0);
}

export function generateInvoiceForAssignment(
  assignment: StudentAssignment,
  structure: FeeStructure,
  term: AcademicTerm,
  boardingStatus: 'Boarding' | 'Day',
  seq: number,
): GeneratedInvoice {
  const applicable = structure.items.filter(i => {
    if (i.cycle === 'One-time' && term.id !== 't1') return false;
    if (i.appliesTo && i.appliesTo !== 'All' && i.appliesTo !== boardingStatus) return false;
    return true;
  });
  const lines = applicable.map(i => ({ description: i.name, glAccountCode: i.glAccountCode, amount: i.amount }));
  const subtotal = lines.reduce((s, l) => s + l.amount, 0);
  const discountPct = assignment.discountPercent || 0;
  const scholarship = assignment.scholarshipAmount || 0;
  const discount = subtotal * (discountPct / 100) + scholarship;
  const total = Math.max(0, subtotal - discount);
  const dueDate = new Date(term.startDate);
  dueDate.setDate(dueDate.getDate() + 14);
  return {
    id: `gi-${Date.now()}-${seq}`,
    invoiceNumber: `AUTO-${term.id.toUpperCase()}-${String(seq).padStart(4, '0')}`,
    studentId: assignment.studentId,
    structureId: structure.id,
    termId: term.id,
    date: term.billingDate,
    dueDate: dueDate.toISOString().split('T')[0],
    lines, subtotal, discount, total,
    status: 'Posted',
    currency: structure.currency,
    autoGenerated: true,
  };
}

export function agingBuckets(invoices: GeneratedInvoice[], asOf: Date = new Date()) {
  const buckets = { current: 0, b30: 0, b60: 0, b90: 0, over90: 0 };
  invoices
    .filter(i => i.status !== 'Paid' && i.status !== 'Cancelled')
    .forEach(i => {
      const due = new Date(i.dueDate);
      const days = Math.floor((asOf.getTime() - due.getTime()) / (1000 * 60 * 60 * 24));
      if (days <= 0) buckets.current += i.total;
      else if (days <= 30) buckets.b30 += i.total;
      else if (days <= 60) buckets.b60 += i.total;
      else if (days <= 90) buckets.b90 += i.total;
      else buckets.over90 += i.total;
    });
  return buckets;
}
